name: oppgave 18
on:
  [ push, workflow_dispatch ]

jobs:
  job1:
    defaults:
      run:
        shell: pwsh
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        
      - name: Login via Az module
        uses: azure/login@v1
        with:
          creds: ${{ secrets.NEWSECRETWORKSHOP }}
          enable-AzPSSession: true 

      - name: 'Run cleanup script'
        uses: azure/powershell@v1
        with:
          inlineScript: ./funcApp/cleanup.ps1 -ResourceGroupName "ahmad-workshop-3lanqvr5abi7i" 
          azPSVersion: "latest"

      - name: 'logout from azure'
        uses: azure/powershell@v1
        with:
          inlineScript: |
            Disconnect-AzAccount -Scope CurrentUser
            az logout
            az cache purge
            az account clear
          azPSVersion: "latest"
    
      

          